name: dart_firebase
description: "Access Firebase Firestore from a REST API"
version: 1.0.0-nullsafety.1
homepage: https://github.com/rodydavis/plugins
issue_tracker: https://github.com/rodydavis/dart_firebase
authors:
- "Kenneth Endfinger <kaendfinger@gmail.com>"
- "Rody Davis Jr <rody.davis.jr@gmail.com>"
environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'
